M48
; DRILL file {KiCad 9.0.1} date 2025-12-19T01:31:38-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-19T01:31:38-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X182.575Y-152.933
X187.425Y-152.933
T2
X182.275Y-155.963
X187.725Y-155.963
M30
